export const CXP_COMPLAINT_LIST_CONTROLS = 1
export const CXP_CHAT_SCREEN_CONTROLS = 2
export const CXP_BATCH_ACTION_POPUP_CONROLS = 3
export const CXP_RATINGS_CONTROL = 4
export const CXP_FUNNEL_FILTER_CONTROLS = 5
export const UNO_USER_DETAILS = 6
